resources:
- name: repo
  type: git
  source:
    uri: https://github.com/concourse/examples.git
    
jobs:
- name: hello-world-job
  plan: 
  - task: hello-world-task
    config:
      platform: linux
      image_resource: 
        type: registry-image
        source:
          repository: busybox
      run:
        path: cat
        args: ["test.txt"]