resources:
- name: repo
  type: git
  source:
    uri: https://github.com/Althammer-Kill/concourse-test
    
jobs:
- name: hello-world-job
  plan: 
  - get: repo
    trigger: true
  - task: hello-world-task
    config:
      platform: linux
      image_resource: 
        type: registry-image
        source:
          repository: busybox
      inputs:
      - name: repo
      run:
        path: cat
        args: ["repo/test.txt"]