resources:
- name: repo
  type: git
  source:
    uri: https://github.com/Althammer-Kill/concourse-test.git
    
jobs:
- name: concourse-test
  plan: 
  - get: repo
    trigger: true
  - task: build
    config:
      platform: linux
      image_resource: 
        type: registry-image
        source:
          repository: mcr.microsoft.com/dotnet/sdk
          tag: "7.0"
      inputs:
      - name: repo
      run:
        dir: "repo"
        path: "dotnet"
        args: ["build"]